version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
	Restart: always
    build:
		context: .
		Dockerfile: Dockerfile.dev
    ports:
      - "4001:8001"
	volumes:
	  - /app/node_modules
	  - .:/app
